### ISSUE TITLE
It's unclear what will happen when you run command

### ISSUE THREAD

**Issue by fedordikarev** [grafana/unused#57]
> For a moment I was a bit scared of running the `unused -gcp.project=some_project -i -filter=kubernetes.io/created-for/pvc/namespace=some_name` command, because I didn't know if it was going to start deleting things right away.

As one option we could rename or add `-interactive` flag. Maybe even `-list-interactive` so it will be clear that not any disk will be deleted running that command.

**Comment by inkel** [comment]
🤔 I'm not sure that changing the name of the flag would make it clearer. Perhaps we should rewrite the programs help/documentation to make it clear.

**Comment by fedordikarev** [comment]
One idea that comes to my mind: we could change flag and make new one: `-mode <mode>` with default `ui` or `interactive`.
And others like `list`, `list-group-by`, `csv-export`, `batch-delete`

**Comment by fedordikarev** [comment]
another idea: introduce flag `-read-only` or `-dry-run` that will disable `delete` functionality

**Comment by inkel** [comment]
Dry run mode has been merged in #61.
